### ISSUE TITLE
Can not create object after restart Egeria server (with JDBC and Kafka)

### ISSUE THREAD

**Issue by MaximVetlugin** [odpi/egeria-connector-xtdb#250]
Hello!

I use this test to ensure that everything fine with Egeria (data stores for example).
[](https://github.com/odpi/egeria/issues/5506#issuecomment-888373241)

When I use RockDB as store for Docs & Tx - all work fine.
I can run this test any time I want.

But when I use JDBC (Postgres) as DocStore & Kafka as TxStore, I can run this test only until restart Egeria (/instance or restart service). 
After restart I have this error:

`org.opentest4j.AssertionFailedError: createValidValueSet ==> Unexpected exception thrown: org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException: OMAG-REPOSITORY-HANDLER-500-001 An unexpected error org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException was returned to createEntity by the metadata server during createValidValueSet request for open metadata access service Digital Architecture OMAS on server paukd-platform-rnd; message was OMAG-REPOSITORY-HANDLER-404-009 A null entity was returned to method createValidValueSet of server paukd-platform-rnd during a request for entity of type ValidValuesSet (guid 7de10805-7c44-40e3-a410-ffc51306801b) and properties of: InstanceProperties{propertyNames=java.util.HashMap$KeyIterator@15c05a20, propertyCount=2, instanceProperties={isDeprecated=PrimitivePropertyValue{primitiveValue=false, primitiveDefCategory=PrimitiveDefCategory{code=1, name='boolean', javaClassName='java.lang.Boolean', guid='3863f010-611c-41fe-aaae-5d4d427f863b'}, instancePropertyCategory=InstancePropertyCategory{typeCode=1, typeName='Primitive', typeDescription='A primitive type.'}, typeGUID='3863f010-611c-41fe-aaae-5d4d427f863b', typeName='boolean'}, qualifiedName=PrimitivePropertyValue{primitiveValue=Set Name Test 0.52808402889591, primitiveDefCategory=PrimitiveDefCategory{code=11, name='string', javaClassName='java.lang.String', guid='b34a64b9-554a-42b1-8f8a-7d5c2339f9c4'}, instancePropertyCategory=InstancePropertyCategory{typeCode=1, typeName='Primitive', typeDescription='A primitive type.'}, typeGUID='b34a64b9-554a-42b1-8f8a-7d5c2339f9c4', typeName='string'}}}

	at org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:83)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:76)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:63)
	at org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3141)
	at training.ds.uad.TrainingBaseLogic.lambda$assertDoesNotThrow$1(TrainingBaseLogic.java:56)
	at training.ds.uad.TrainingBaseLogic.executionTime(TrainingBaseLogic.java:110)
	at training.ds.uad.TrainingBaseLogic.assertDoesNotThrow(TrainingBaseLogic.java:55)
	at training.ds.uad.TrainingBaseLogic.assertDoesNotThrow(TrainingBaseLogic.java:49)
	at training.ds.uad.egeria.digitalarchitecture.PerformanceTest.createSetGuid(PerformanceTest.java:52)
	at training.ds.uad.egeria.digitalarchitecture.PerformanceTest.testPerformance(PerformanceTest.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: PropertyServerException{reportedHTTPCode=500, reportingClassName='org.odpi.openmetadata.commonservices.ffdc.RESTExceptionHandler', reportingActionDescription='createValidValueSet', reportedErrorMessage='OMAG-REPOSITORY-HANDLER-500-001 An unexpected error org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException was returned to createEntity by the metadata server during createValidValueSet request for open metadata access service Digital Architecture OMAS on server paukd-platform-rnd; message was OMAG-REPOSITORY-HANDLER-404-009 A null entity was returned to method createValidValueSet of server paukd-platform-rnd during a request for entity of type ValidValuesSet (guid 7de10805-7c44-40e3-a410-ffc51306801b) and properties of: InstanceProperties{propertyNames=java.util.HashMap$KeyIterator@15c05a20, propertyCount=2, instanceProperties={isDeprecated=PrimitivePropertyValue{primitiveValue=false, primitiveDefCategory=PrimitiveDefCategory{code=1, name='boolean', javaClassName='java.lang.Boolean', guid='3863f010-611c-41fe-aaae-5d4d427f863b'}, instancePropertyCategory=InstancePropertyCategory{typeCode=1, typeName='Primitive', typeDescription='A primitive type.'}, typeGUID='3863f010-611c-41fe-aaae-5d4d427f863b', typeName='boolean'}, qualifiedName=PrimitivePropertyValue{primitiveValue=Set Name Test 0.52808402889591, primitiveDefCategory=PrimitiveDefCategory{code=11, name='string', javaClassName='java.lang.String', guid='b34a64b9-554a-42b1-8f8a-7d5c2339f9c4'}, instancePropertyCategory=InstancePropertyCategory{typeCode=1, typeName='Primitive', typeDescription='A primitive type.'}, typeGUID='b34a64b9-554a-42b1-8f8a-7d5c2339f9c4', typeName='string'}}}', reportedErrorMessageId='OMAG-REPOSITORY-HANDLER-500-001', reportedErrorMessageParameters=[OMAG-REPOSITORY-HANDLER-404-009 A null entity was returned to method createValidValueSet of server paukd-platform-rnd during a request for entity of type ValidValuesSet (guid 7de10805-7c44-40e3-a410-ffc51306801b) and properties of: InstanceProperties{propertyNames=java.util.HashMap$KeyIterator@15c05a20, propertyCount=2, instanceProperties={isDeprecated=PrimitivePropertyValue{primitiveValue=false, primitiveDefCategory=PrimitiveDefCategory{code=1, name='boolean', javaClassName='java.lang.Boolean', guid='3863f010-611c-41fe-aaae-5d4d427f863b'}, instancePropertyCategory=InstancePropertyCategory{typeCode=1, typeName='Primitive', typeDescription='A primitive type.'}, typeGUID='3863f010-611c-41fe-aaae-5d4d427f863b', typeName='boolean'}, qualifiedName=PrimitivePropertyValue{primitiveValue=Set Name Test 0.52808402889591, primitiveDefCategory=PrimitiveDefCategory{code=11, name='string', javaClassName='java.lang.String', guid='b34a64b9-554a-42b1-8f8a-7d5c2339f9c4'}, instancePropertyCategory=InstancePropertyCategory{typeCode=1, typeName='Primitive', typeDescription='A primitive type.'}, typeGUID='b34a64b9-554a-42b1-8f8a-7d5c2339f9c4', typeName='string'}}}, createValidValueSet, Digital Architecture OMAS, paukd-platform-rnd, org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException, createEntity], reportedSystemAction='The system is unable to process the request because of an internal error.', reportedUserAction='Verify the sanity of the server.  This is probably a logic error.  If you can not work out what happened, ask the Egeria community for help.', reportedCaughtException=null, reportedCaughtExceptionClassName='null', relatedProperties=null}
	at org.odpi.openmetadata.commonservices.ffdc.RESTExceptionHandler.throwPropertyServerException(RESTExceptionHandler.java:283)
	at org.odpi.openmetadata.commonservices.ffdc.RESTExceptionHandler.detectAndThrowStandardExceptions(RESTExceptionHandler.java:126)
	at org.odpi.openmetadata.commonservices.ffdc.rest.FFDCRESTClient.callGUIDPostRESTCall(FFDCRESTClient.java:194)
	at org.odpi.openmetadata.accessservices.digitalarchitecture.client.ValidValuesManager.createValidValueSet(ValidValuesManager.java:186)
	at training.ds.uad.egeria.digitalarchitecture.PerformanceTest.lambda$createSetGuid$0(PerformanceTest.java:57)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:72)
	... 73 more

Process finished with exit code -1
`

Egeria 3.2
Connector 3.2 SNAPSHOT

**Comment by cmgrote** [comment]
I suspect this is related to the configuration ordering quirks described in #246.  My hunch is that some components of the configuration given that behaviour are defaulting to in-memory-only, so that as soon as the XTDB node is restarted (since there is no persistence for some portion of the configuration) data is lost.

Can you 🙏 try to change the ordering of the configuration as described in #246, and then confirm:

1. Does it fix the issue described in #246?
2. Does it also resolve this issue?

**Comment by cmgrote** [comment]
Closing per wrap-up comments on #246
